name: 🛠 Task
description: Internal development task
title: "[TASK]: "
labels: [task]
type: task
body:
  - type: textarea
    attributes:
      label: Describe the task
      description: A short explanation of what needs to be done.
    validations:
      required: true

