name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != dev ]]; 
          then
            echo "Error: Pull request must come from 'dev' when going into 'main'"
            exit 1
          fi
