name: On Open PR to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

permissions:
pull-requests: write
contents: read

jobs:
  apply-release-template:
    if: github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read template
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --body-file .github/PULL_REQUEST_TEMPLATE/release_PR_template.md
        env:
          GH_TOKEN: ${{ github.token }}
